### ISSUE TITLE
Angular 2 as framework for SPA's & business tools

### ISSUE THREAD

**Issue by moniecodes** [ModaOperandi/agora#12]
**Some Pros:** 

- Already a lot of infrastructure & experience @ moda
- Large & involved community, excellent docs & tutorials  + google!
- Full clientside MVC framework for SPA
- Defined app structure, component layout, e2e, routing & services structure
- Typescript, component based, rxjs!

**Some Cons:**

- Heavier, can get slow
- Dependency injection can get nuanced
- Content projection and reuse limitations
- Angular 1 makes community divisive

**Comment by rlmartin** [comment]
Closing this per discussion related to https://github.com/ModaOperandi/agora/pull/26
