### ISSUE TITLE
React vs Angular

### ISSUE THREAD

**Issue by rlmartin** [ModaOperandi/agora#15]

**Comment by chasezimmy** [comment]
https://modaoperandi.atlassian.net/wiki/spaces/EN/pages/140050578/2019-07-31+Meeting+notes

Good to note, this was discussed in the FE Guild. There was a unanimous decision to go with React.

**Comment by 3ZsForInsomnia** [comment]
Awesome! @rlmartin @ruxy and also whoever else this will be presented/argued to - what is the protocol/what do you want to see for this? A presentation or doc explaining the reasoning? What level of depth should this go into?

**Comment by ruxy** [comment]
@3ZsForInsomnia Next steps would be creating a pull request with some of the key items of the discussion (pros / cons) and then presenting at the agora council. You can look at this one for inspiration: https://github.com/ModaOperandi/agora/pull/17.

**Comment by 3ZsForInsomnia** [comment]
@ruxy Created a PR. I summarized the notes for preference for React, and trialing Typescript. Ready for change requests. https://github.com/ModaOperandi/agora/pull/26
