### ISSUE TITLE
Can/should we simplify the stack/platform?

### ISSUE THREAD

**Issue by rlmartin** [ModaOperandi/agora#53]
What would this even look like?

Vlad to report back with findings from migrating existing services onto the platform. He is actively migrating Scala services. He also has a potential strategy for Python/Ruby services (from CI/CD onwards, but not necessarily codegen).

Should also document an overall approach to migration. Can we kill "old" AWS accounts that still have prod resources in them? How do we approach data: migration, no migration, encapsulation, etc?

**Comment by ruxy** [comment]
Done.
