### ISSUE TITLE
Proper logging data flow

### ISSUE THREAD

**Issue by rlmartin** [ModaOperandi/agora#61]
Current state: some things push directly to New Relic Logs (via a sidecar), some other things (fewer things) push to CloudWatch Logs then get forwarded to NR.

How are we liking New Relic Logs?

Some people would additionally like to get logs into Snowflake for querying.

We should also clean up the log format so it is more easily parseable.

**Comment by ruxy** [comment]
Q: Is there a way to send from NR to Snowflake?

**Comment by jackfarzan** [comment]
Docs for EKS platform's NR practices https://modaoperandi.atlassian.net/wiki/spaces/DEVOPS/pages/171999337/New+Relic

**Comment by ruxy** [comment]
Next steps: try sending logs to snowflake for a few days to see what the cost runs up to

**Comment by bjmiller** [comment]
We're thinking that we should just keep logs in glacier for now.

**Comment by bjmiller** [comment]
Also, we need a policy for how long we keep logs.

**Comment by jackfarzan** [comment]
To start, we should log anything that touches user info (login, payment, order) as well as CDNs. We can put these logs in deep archive in AWS, and restore when needed. We'll store logs going back to a year.
Logs to archive:
* user-api
* mojo
* Discovery & mojo CDNs
* ???

**Comment by ruxy** [comment]
This now exists! Last step moving to SDLC.
